ublue-os/config

build/ublue-os-just/justfile
=> feat: add some justfile shortcuts

files/etc/udev/rules.d/50-usb-realtek-net.rules, rpmspec/ublue-os-udev-rules.spec
Addresses #24 , but I want to ensure it works as expected before merging.
=> feat: add udev rules for 2.5G realtek usb

.github/workflows/build.yml
Freight train comin' down the track, chugga chugga chugga.
=> chore(ci): turn on the merge queue

Containerfile
jntesteves recommends using this repo instead of his.
=> feat: update game devices repo

build/ublue-os-just/main.just
We can add multiple things in here, but starting with a podman system prune.
=> feat(just): add clean shortcut

build/ublue-os-just/main.just
Removes unused flatpaks as well as temp files and repo metadata from ostree
=> feat(clean): Implement cleanup for package managers

files/usr/lib/systemd/system/flatpak-system-update.service, files/usr/lib/systemd/user/flatpak-user-update.service
Improves upon the existing flatpak update service unit.
closes #14
=> feat: add repair and uninstall unused flatpak maintenance tasks

build/ublue-os-just/main.just
This effectively let's any downstream image "bolt-on" the bazzite gaming experience - awesome pattern!
=> feat(just): add bazzite-arch shortcut

build/ublue-os-just/30-distrobox.just
See: https://github.com/ublue-os/arch-distrobox/
=> feat: Use new arch-distrobox image when creating an arch container

build/ublue-os-just/10-update.just
Or is it maybe better to have it separate and call the shortcut like update-firmware?
=> feat(just): add fwupd firmware updates to justfile

build/ublue-os-just/10-update.just
Add support for installations that use ublue-update
Closes #142 
Please review carefully, we don't want to break this stuff
=> feat(just): add support for ublue-update

build/ublue-os-just/00-default.just
I made it really easy for users to use distrobox-git instead of the system distrobox if desired
=> feat: Added a way to use distrobox-git in 00-default.just

build/ublue-os-just/30-distrobox.just
Now it is easier to create an Alma or Centos distrobox.
=> feat(just): Added Alma Linix and Centos to 30-distrobox.just

build/ublue-os-just/70-nix.just, build/ublue-os-just/ublue-os-just.spec
there were quite a bit of nix stuff added possibly with more nix stuff added
=> feat(just): Created 70-nix.just with nix installation, uninstallation, and configuration

build/ublue-os-just/00-default.just
Removing install and shell for now, but leaving uninstall there since this conflicts with host stuff.
=> fix(just): remove brew shortcuts

build/ublue-os-just/header.just
=> feat: Link to ublue just documentation from ujust default

build/ublue-os-just/etc-distrobox/distrobox.ini, build/ublue-os-just/ublue-os-just.spec
Allows users to assemble Bluefin CLI and Wolfi distrobox images
=> feat(distrobox): Add Bluefin CLI & Wolfi (DX)

build/ublue-os-just/etc-distrobox/apps.ini
This was in bluefin but useful everywhere and we've got a few people using it so let's add it!
=> feat(just): add a machine learning box

build/ublue-os-just/60-custom.just
=> feat: add check-local-overrides just command

build/ublue-os-just/40-nvidia.just
=> feat: add just commands for nvidia-optimus configuration

Containerfile
=> fix: update sunshine.rules location

.gitattributes
=> fix: github linguist detection of various file types

.github/workflows/build.yml
Of course, also this also builds when merged.
Closes: #237
=> chore: only run scheduled builds weekly

build/ublue-os-just/00-default.just
https://github.com/ublue-os/config/issues/247
=> feat: add device-info command

build/ublue-os-just/00-default.just
remove just recipe for fixing screenshare since xwaylandvideobridge is no longer have .desktop file
=> feat: remove fixscreenshare

build/ublue-os-just/ublue-tips/15-ublue-config.md
=> fix(motd): spelling

.github/workflows/build.yml
=> chore(ci): Update builder to 24.04

build/ublue-os-just/ublue-os-just.spec
=> fix: missing source in just rpm

build/ublue-os-just/ublue-os-just.spec
=> chore: update version number of just.spec

files/usr/etc/containers/policy.json
Match behavior of other key paths and read the toolbox pubkey from /etc
=> chore(containers/policy): Read toolbox pubkey from /etc

build/ublue-os-just/etc-profile.d/user-motd.sh
=> feat: Prevent double sourcing of user-motd

build/ublue-os-just/00-default.just
We're removing chsh from the image, this removes the just snippet.
=> fix(just): drop chsh snippet

build/ublue-os-luks/luks-enable-tpm2-autounlock
https://www.riscure.com/security-highlight-a-further-look-at-faultpm-deepest-secrets/
=> feat: add warning about faulTPM

build/ublue-os-luks/luks-enable-tpm2-autounlock
https://github.com/rhboot/shim/blob/main/README.tpm
=> feat: use PCR 14 as well for tpm2 unlock

files/etc/rpm-ostreed.conf
https://github.com/coreos/rpm-ostree/pull/4974
https://github.com/ublue-os/main/issues/632
=> feat: set Recommends=false by default to minimize local layer size

files/usr/ublue-os/homebrew/kubernetes.Brewfile
=> feat(just): add krew to k8s tools

build/ublue-os-luks/luks-enable-tpm2-autounlock
=> fix: luks-enable-tpm2-autounlock

build/ublue-os-just/30-distrobox.just, build/ublue-os-just/etc-distrobox/apps.ini, build/ublue-os-just/ublue-os-just.spec
since we have now deprecated the obs-studio-portable image. i am removing the ujust for it in main
=> feat(just): remove obs-studio-portable

files/etc/udev/rules.d/50-steam-horipad-controller.rules
add steam horipad udev rules
udev rules tested on my bazzite HTPC
=> feat(horipad): udev rules for steam horipad

build/ublue-os-just/00-default.just
I never remember the commands for checking the bios version and I am too lazy to reboot into bios
example output:
```
Manufacturer: ASRock
Product Name: X670E Pro RS
Version: 3.06
Release Date: 07/26/2024
```
```
Manufacturer: Framework
Product Name: FRANMCCP04
Version: 03.07
Release Date: 12/26/2024
```
=> feat(just): add bios-info
