ublue-os/config

.github/workflows/build.yml
This builds an hour earlier than main so it can be ingested
=> chore: add a scheduled build

files/etc/udev/rules.d/80-wooting.rules
this adds new new wooting udev rules, but keeps the group "wheel" instead of using "input" as we are trying to sort out some issues related to groups
=> feat: add new wooting udev rules

.github/workflows/build.yml
See my PRs in -main, -akmods, -nvidia. This change breaks -nvidia, as it tries to install ublue-os-just again.
- Build ublue-os-just in -config
- Adjust build time to be more in line with quay.io/fedora-ostree-desktops
=> feat: New akmods build process

.github/workflows/build.yml
Closes #31 
Want to let a build run and make sure it creates tags as expected, but should appropriately "unversion" the config builds.
=> chore(ci): remove unused fedora major version

Containerfile, README.md, rpmspec/ublue-os-update-services.spec
This modifies the ublue-os-update-services RPM to use the more standard paths agreed on in proposal for standardized locations.
See: https://github.com/orgs/ublue-os/discussions/149
=> refactor: pretty up update-services standard path

Containerfile, README.md, rpmspec/ublue-os-udev-rules.spec
This modifies the ublue-os-udev-rules RPM to use the more standard paths agreed on in proposal for standardized locations.
See: https://github.com/orgs/ublue-os/discussions/149
Also, tweaks the description of RPM to be more generic since it's not just game controllers any more.
=> refactor: pretty up udev-rules standard path

build/ublue-os-just/main.just, build/ublue-os-just/ublue-os-just.sh
This change allows us to recommend using just includes by default.
More: #48 
These changes are only tested manually by creating a test.sh file in `/etc/profile.d/` manually. I found out that it does not work in `fish` and other POSIX incompatible shells by default, those users need to create the alias manually.
_Required changes after merge: Documentation section about `just` instructing users to create their own "dummy" justfile._ DONE
=> chore: make `just` unstable by default

build/ublue-os-just/nvidia.just
Setting nomodeset prevents nvidia-powerd from ever loading
See: https://github.com/ublue-os/nvidia/issues/71
=> Remove nomodeset from nvidia kargs

build/ublue-os-just/main.just, build/ublue-os-just/nvidia.just
This add secure boot signing key for akmods to the `main.just` and renames the legacy version of the command in `nvidia.just` to be specific for older nvidia-only key.
=> feat: support new akmod signing key in just files

build/ublue-os-just/ublue-os-just.sh
When a user does not have a $HOME/.justfile, provide a default which uses `just includes` from our provided files as documented on the website.
https://ublue.it/guide/just/
=> feat: create default justfile for users

Containerfile, files/etc/systemd/system/rpm-ostreed-automatic.timer, files/usr/lib/systemd/system/flatpak-system-update.service, files/usr/lib/systemd/system/flatpak-system-update.timer, files/usr/lib/systemd/user/flatpak-user-update.service, files/usr/lib/systemd/user/flatpak-user-update.timer, rpmspec/ublue-os-update-services.spec
This adds an override for the Fedora stock rpm-ostreed-automatic.timer and sets it and both the user and system flatpak timers to always run at 4:00AM localtime. If the host machine is suspended or powered down   during that time, the timers will execute on next boot. 
The flatpak update services have been simplified to not request install and to be simple services like rpm-ostreed-automatic.service.
Closes #26
=> feat: standardize flatpak/rpm-ostree update timers

build/ublue-os-just/ublue-os-just.spec, files/usr/etc/containers/policy.json, rpmspec/ublue-os-udev-rules.spec
Fixes the bug by adding to the containers/policy.json. 
Incidentally fixes typos in dates on spec files which were found during testing.
closes #82
=> fix: allow podman to use containers-storage transport locally

build/ublue-os-just/nvidia.just
On June 17, 2023 we stopped using the legacy nvidia key for signing nvidia kmods, thus we can remove this command which make it easier to import the key, which doesn't even exist anymore and fails.
=> fix: remove vestigal just command for legacy nvidia key

files/etc/systemd/system/rpm-ostreed-automatic.timer
Resolves #87
According to #87, automated updates have not been running since the systemd service timer is not persistent.  Therefore, the machines must be running at 4am for the systemd service to be triggered.
This PR switches the service to persistent so it runs on next boot.
> Persistent=
Takes a boolean argument. If true, the time when the service unit was last triggered is stored on disk. When the timer is activated, the service unit is triggered immediately if it would have been triggered at least once during the time when the timer was inactive. Such triggering is nonetheless subject to the delay imposed by RandomizedDelaySec=. This is useful to catch up on missed runs of the service when the system was powered down. Note that this setting only has an effect on timers configured …
=> fix: set rpm-ostree updates as persistent

build/ublue-os-just/main.just
So they show up when you type `just`.
=> feat(just): update descriptions for shortcuts

files/usr/etc/systemd/system/rpm-ostreed-automatic.timer.d/override.conf, files/usr/lib/systemd/system/flatpak-system-update.timer, files/usr/lib/systemd/user/flatpak-user-update.timer, rpmspec/ublue-os-update-services.spec
This should fix #89 by ensuring that flatpak update timers always run at least two minutes after system boot.
Also, randomized delay was added for both flatpak update and rpm-ostreed-automatic timers to prevent the download and system load from always hitting at exactly the same time.
=> fix: run flatpak two minutes after boot

files/usr/etc/containers/policy.json
Fixes #102.
Adds `oci-archive` and `docker-archive` with `insecureAcceptAnything` to the default container policy. This allows `docker-compose` image builds using BuildKit to transfer images to Podman.
=> Allow archive formats in container policy

build/ublue-os-just/main.just
No downside for AMD, simply does nothing.
=> fix: Always use --nvidia when creating distrobox containers

build/ublue-os-just/nvidia.just
Use `--delete-if-present` so it would not fail if `nomodeset` not exists
=> fix(just): use delete-if-present in set-kargs-nvidia

build/ublue-os-just/ublue-os-just.spec
Fixes #120 
I tested this locally to ensure the resulting paths are correct. Should be good to go.
=> fix: fix invalid justfile include paths

files/usr/lib/systemd/system/flatpak-system-update.service, files/usr/lib/systemd/user/flatpak-user-update.service
This PR fixes issue #117, by making all the commands in the ```flatpak-system-update``` service run from ```ExecStart=```, which prevents them from being automatically killed from time to time.
=> Fix #117 (flatpak update failing)

build/ublue-os-just/10-update.just, build/ublue-os-just/ublue-os-just.spec, files/usr/etc/systemd/system/rpm-ostreed-automatic.service.d/override.conf, files/usr/lib/systemd/system/flatpak-system-update.service, files/usr/lib/systemd/user/flatpak-user-update.service, rpmspec/ublue-os-update-services.spec
This PR prevents automatic update services from running on a metered connection (see #113 for more details).
Explanation:
- ```/bin/bash -c``` is needed because systemd runs binaries, not shell scripts
- ```busctl get-property org.freedesktop.NetworkManager /org/freedesktop/NetworkManager org.freedesktop.NetworkManager Metered``` gets the value of the metered connection property
- ...but it doesn't just return the number, also some symbols behind it, so we trim them with ```| cut -c 3-```
- ```== @(2|4)``` checks if the result is either 2 (NM_METERED_NO) or 4 (NM_METERED_GUESS_NO), as per documentation:
- the service only runs if the above code returns a success code
Regarding DE app stores and such: GNOME software seems to already have support for not running updates on a metered …
=> feat: check metered connection before automatic updates

build/ublue-os-just/40-nvidia.just
This is required since nvidia container toolkit 1.14
=> fix: add nvidia device argument to cuda test

build/ublue-os-just/40-nvidia.just
The original `cuda-vector-add` image was about 2GB but this one is only 117MB.  A lot lighter just to test if your container nvidia CUDA is working.
=> refactor: use a slimmer image for the nvidia cuda test

build/ublue-os-just/00-default.just, build/ublue-os-just/build.sh, build/ublue-os-just/ublue-os-just.spec, build/ublue-os-just/ujust
This adds a little shim, `/usr/bin/ujust`, to run, `just --unstable --justfile /usr/share/ublue-os/justfile`.
I think this is a much cleaner way to run our `just` tasks than putting a `~/.justfile` in the home directory, for a number of reasons. One of them is that this does not require aliasing `just=just --unstable`, and another is that a user can actually have their own `~/.justfile` with no regard for including our global one.
I didn't remove the `just` aliases from the shell dotfiles, because I'm not sure what breaking changes that might cause -- documentation, for sure, but also does yafti or anything else depend on that?
~~Also to be honest I'm not sure where the default just alias comes from. I didn't actually look yet :P~~ _the alias comes from this repo_
I did this because I …
=> feat: add ujust, add chsh just task

build/ublue-os-just/ublue-os-just.sh
This fixes issue #100 by adding a comment to the boilerplate justfile in the home directory, stating that this file can be edited and directing the user to the documentation. In my opinion, we should keep this short, and just point the user to the documentation, but if you feel like this is not enough, I can make this more elaborate.
=> feat(just): add comment to boilerplate justfile (fix #100)

files/etc/udev/rules.d/85-sunshine.rules, rpmspec/ublue-os-udev-rules.spec
This PR fixes issue #119 by adding Sunshine udev rules. These don't seem to be hardware-specific or regularly updating (as per [documentation](https://github.com/LizardByte/Sunshine/blob/master/docs/source/about/usage.rst)), so it's fine to include them as a static file.
=> feat(udev): add Sunshine udev rules (fix #119)

Containerfile, files/etc/udev/rules.d/85-sunshine.rules, rpmspec/ublue-os-udev-rules.spec
This renames the files 70-opentabletdriver.rules and and 85-sunshine.rules to add "-ublue" before ".rules" and increment the numbered prefix by one.
The "-ublue" ensures we'll never have a name collision which prevents their respective official RPMs from installing.
The increment attempts to assure that the official rules will take priority should the official RPM be installed.
FYI - @ArtikusHG / @KyleGospo
=> fix: rename Sunshine/OpenTabletDriver udev rules to avoid collissions

build/ublue-os-just/10-update.just
While metadata may be up to date, firmware updates may still be available. When this fails, the script refuses to continue so force a refresh so that newer firmware may still be installed
=> fix(firmware-update): Force metadata refresh

.github/workflows/build.yml
Move build schedule back for official images
=> chore(ci): Build at 1:30 PM

files/etc/udev/rules.d/10-switch.rules
Just to make having to reboot a jigged Switch easier, since I cannot get ns-usbloader to run at all.
=> feat: add udev rule for an RCM'd Nintendo Switch to allow rootless payload injection

files/etc/udev/rules.d/92-viia.rules
Keychron keyboard hardware enablement, credit to HikariKnight and Javvy for development and testing
=> feat: add udev rule to enable usevia.app in supported browsers for Keychron keyboard configuration

build/ublue-os-just/00-default.just, build/ublue-os-just/10-update.just, build/ublue-os-just/20-clean.just, build/ublue-os-just/30-distrobox.just, build/ublue-os-just/40-nvidia.just, build/ublue-os-just/50-akmods.just, build/ublue-os-just/60-custom.just
This formats the justfiles to be able to pass the action with #155. Should be merged **first**.
=> chore(just): format justfiles

.github/workflows/build.yml
This PR makes the build action fail when ``just --fmt --check`` fails (#152).
**Note: currently, none of the justfiles we have here pass the formatting check. #156 must be merged first.**
=> feat: check just syntax in build action (fix #152)

build/ublue-os-just/00-default.just
This pull request will make homebrew easy to install and remove on all ublue varients
=> feat(just): added homebrew installation

build/ublue-os-just/ublue-os-just.spec
The nix justfile was overwriting ujust instead of being copied over to the directory containing the rest of the justfiles
=> fix(just): Copy nix justfile to correct location, restore ujust

build/ublue-os-just/10-update.just
`just update-firmware` shows an error because of a  non zero exit value. That could lead to confusion by the end user. For example:
```
just update-firmware 
...SNIP...
Devices with the latest available firmware version:
• UEFI dbx
No updates available
error: Recipe `update-firmware` failed on line 134 with exit code 2
```
The current PR lets just ignore the exit message on the `update-firmware` command, so it would not show an error when the exit code is non zero.
Fixes: https://github.com/ublue-os/bluefin/issues/722
=> fix(just): handle non zero exit code update-firmware

build/ublue-os-just/build.sh, build/ublue-os-just/ublue-os-just.spec, build/ublue-os-just/ugum
This should help start the process of addressing #148 as it will let us provide basic replacement for gum on systems that lack it with minimal options which in turn lets us shrink down the amount of just commands we have greatly.
Currently it only does choose dialogs, but before merging i want to implement the confirm dialog too.
Return values will be identical to what you would expect from gum so in the most basic use cases it will be a 1:1 drop in, assuming you do not need anything more fancy than the defaults from gum.
=> feat: add gum helper for choose dialogs

files/etc/udev/rules.d/99-thinkpad-thresholds-udev.rules
Allows user to modify the battery charge thresholds without password prompt. The rule was copied from [marcosdalvarez/thinkpad-battery-threshold-extension](https://gitlab.com/marcosdalvarez/thinkpad-battery-threshold-extension). Works only on ThinkPads.
=> feat(udev): add udev rule for promptless charing threshold changes 

.github/workflows/build.yml, build/ublue-os-just/00-default.just, build/ublue-os-just/ublue-os-just.sh, build/ublue-os-just/ublue-os-just.spec
=> fix: Use import for just

build/ublue-os-just/ublue-os-just.spec, build/ublue-os-just/ugum, build/ublue-os-just/ujust
Basic housekeeping after today's changes, let's slow roll this one
=> chore: Clean up just packages

build/ublue-os-just/30-distrobox.just
This is to fix: https://github.com/ublue-os/config/issues/106
I decided to go with the official toolbox images for RHEL which will require users to log in. I did add a check to confirm the user is logged in to `registry.redhat.io` before attempting to create the distrobox.
For the UBI images, I went with the URL that does not require authentication to pull them down.
=> feat(just): Add RHEL Toolboxes and UBI Images

build/ublue-os-just/ublue-os-just.spec
Addresses #187 
Adds a postinstall step to the rpm spec file which will run
`just --completion bash | perl -pe 's/([\(_" ])just/\1ujust/g' > %{_datadir}/bash-completion/completions/ujust`
`just --completion bash` generates a just bash completion file and outputs it to STDOUT
`perl -pe 's/([\(_" ])just/\1ujust/g' > %{_datadir}/bash-completion/completions/ujust` rewrites the output using perl so that the bash completion will work for ujust and writes the output to an ujust bash completion file.
edit: replaced `perl -pe` with `sed -E` as we found out the regex worked in that and perl is not guaranteed to be on potential systems the rpm will be installed on
=> feat(just): Generate tab completion for ujust

build/ublue-os-just/00-default.just, build/ublue-os-just/10-update.just, build/ublue-os-just/20-clean.just, build/ublue-os-just/30-distrobox.just, build/ublue-os-just/40-nvidia.just, build/ublue-os-just/50-akmods.just, build/ublue-os-just/60-custom.just, build/ublue-os-just/70-nix.just
This patch, when complete will be the second step in addressing #148 now that we have `ugum` on all images which solved the need of a standardized way to select between options.
This is something that i will be chipping away at when i am able to.
Naming scheme for just recipes (draft) will be:
- `setup-` Used when the recipe provides a way to install and remove something (configuration can also be added here)
- `configure-` Used to configure something that is pre-installed on the ublue system (maybe shorten to `config-`?)
- `install-` Used by recipes where there is no functionality other than install
- `remove-` used by `remove-brew` due to the issues we got reported where it broke flatpak,  please ignore
- `toggle-` switch something on/off like for example `toggle-gnome-vrr` (if it makes …
=> feat(just): combine several just commands into toggles or choices

build/ublue-os-just/00-default.just
I think it would be pretty handy if there was like a collection of shortcuts for log messages/crash reports.
=> feat(just): added log messages shortcut from journalctl to 00-default.just

build/ublue-os-just/70-nix.just
=> fix(just): add missing quotes in setup-fleek

build/ublue-os-just/30-distrobox.just, build/ublue-os-just/build.sh, build/ublue-os-just/lib-ujust/libdistrobox.sh, build/ublue-os-just/lib-ujust/ujust.sh, build/ublue-os-just/ublue-os-just.spec, files/usr/etc/distrobox/apps.ini, files/usr/etc/distrobox/distrobox.ini
=> feat(just): add distrobox tooling to just and cleanup distrobox just file

build/ublue-os-just/50-akmods.just
See: https://github.com/ublue-os/akmods/pull/115
=> chore: Drop gamepad configuration script thanks to changes in ublue-os/akmods no longer requiring it

build/ublue-os-just/30-distrobox.just
The 2 calls had 2 args in the wrong order
=> fix(just): Call AssembleList with the correct arguments when installing distrobox-apps

build/ublue-os-just/etc-profile.d/user-motd.sh, build/ublue-os-just/ublue-os-just.spec
Changes are:
1. allow /usr/libexec/ublue-motd as executable, dynamic motd
2. change to /etc/user-motd for static motd, allowing choice to customizate user-motd at runtime if pre-generated is not desired
=> feat: add more flexibility to user-motd

build/ublue-os-just/30-distrobox.just, build/ublue-os-just/lib-ujust/libdistrobox.sh
Relevant bug: https://github.com/89luca89/distrobox/issues/1146
UBI images are fine, they can stay.
=> chore(just): Remove rhel8 and rhel9 toolbox images due to severe incompabilities with distrobox

build/ublue-os-just/lib-ujust/libdistrobox.sh
Fixes a bug that Noel found where if you assemble ALL containers, it would try to do it 2 times and freeze on the 2nd try.
=> fix(just): correctly return after replacing all containers using Assemble

build/ublue-os-just/70-nix.just
Sometime in December 2023, fleek changed their install instructions.
this updates the setup-fleek recipe with the new install command for fleek and fixes #202
=> fix(just): update fleek install to the new 0.10x command

build/ublue-os-just/lib-ujust/libdistrobox.sh
`Distrobox` function was accidentally passing the last argument 2 times, the 2nd time as an "extra" argument
=> fix(just): pass extra arguments from the correct position in the array

build/ublue-os-just/00-default.just, build/ublue-os-just/build.sh, build/ublue-os-just/etc-profile.d/brew.sh, build/ublue-os-just/ublue-os-just.spec
This PR basically copies the brew installer logic from bluefin:
https://github.com/ublue-os/bluefin/blob/main/usr/etc/profile.d/brew.sh
https://github.com/ublue-os/bluefin/blob/main/Containerfile#L104
only change is using `curl https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | /usr/bin/bash -c` instead of having the install script directly on the image, might be better to directly pull these scripts down when building to keep consistency
=> feat: initial brew installer

build/ublue-os-just/00-default.just
This PR adds the missing alias for `brew-install` in 00-default.just
=> fix: add brew alias

build/ublue-os-just/00-default.just
`systemctl reboot --firmware-setup` doesn't support this.
That command calls: `org.freedesktop.login1.Manager SetRebootToFirmwareSetup`, which is the DBUS interface of `systemd-logind`.
=> chore(just): Message the user that rebooting to Legacy BIOS from OS is not supported

build/ublue-os-just/lib-ujust/libformatting.sh
this is to avoid having to pass `${n}` along with the text for usability
=> fix(just): make Urllink remove formating at the end of hyperlink

build/ublue-os-luks/90-ublue-luks.conf, build/ublue-os-luks/build.sh, build/ublue-os-luks/ublue-os-luks.spec
This enables any install to regenerate initramfs and automatically pickup these options for auto LUKS unlock on boot.
Closes: ublue-os/main#593
=> feat: add tpm/fidopkcs11 LUKS unlock config to dracut

scripts/fix-key-and-update.sh
Adds a script which can be executed by users who are on an image signed by an older cosign key pair.
=> chore: add fix-key-and-update.sh script to resolve cosign pub key issues

build/ublue-os-just/etc-distrobox/apps.ini, build/ublue-os-just/etc-distrobox/distrobox.ini
I recently was made aware of this image's existence, figured it should be added to the distrobox ini manifest.
=> feat: Add arch amdgpupro image to distrobox.ini manifest

build/ublue-os-luks/luks-disable-tpm2-autounlock, build/ublue-os-luks/luks-enable-tpm2-autounlock, build/ublue-os-luks/ublue-os-luks.spec
The previous version of the tpm2 script did not fail out when encountering unsupported configurations. This script is narrowly focused at enabling tpm2 decryption for root devices. By default we expect this to be configured via the installer.
This script will now fail out if it cannot find the disk. The disk is determined via the kernel commandline instead of /etc/crypttab. It still only supports a single disk. It now also provides hints on why the script has failed and the commands to run to disable and/or enable.
=> refactor: Rewrite luks tpm2 script.

build/ublue-os-just/00-default.just
`ujust device-info` seems to be broken since this commit: [feat(just): add flatpak list to device-info](https://github.com/ublue-os/config/commit/581c0ed81bc88a1384d76dd3918b9af73e3ee503)
```
❯ ujust device-info
Gathering device info...
/run/user/1000/just/just-ZKOZ4x/device-info: line 120: syntax error near unexpected token `('
/run/user/1000/just/just-ZKOZ4x/device-info: line 120: `fpaste <(rpm-ostree status) <(fpaste --sysinfo --printonly) <<(flatpak list --columns=application,version,options)'
error: Recipe `device-info` failed with exit code 2
```
Even tho manually running the script works fine, I think the `<<` part is what's breaking this, even tho running the script manually from terminal works just fine:
```
❯ fpaste <(rpm-ostree status) <(fpaste --sysinfo --printonly) <<(flatpak …
```
=> fix: ujust device-info script

build/ublue-os-just/10-update.just, build/ublue-os-just/ublue-os-just.spec
It will now toggle the auto update services relevant for the system depending on ublue-update being present or not.
I was originally under the impression that ublue-update was present in main 😅 this is fixed now (and also accounts for people adding ublue-update to their custom main images)
=> fix(just): make toggle-updates check if ublue-update is installed

files/etc/rpm-ostreed.conf
This causes issues with people in chat "I added this package and it didn't bring libvirt" etc.
In hindsight let's back this out, there's no reason to deviate from fedora on this one.
=> revert: "feat: set Recommends=false by default to minimize local layer size"

files/etc/udev/rules.d/30-linksys-ae1200.rules
This reverts commit dbf4dd3485de680528a6b200d344072d129f2304.
For justification please see:
https://github.com/ublue-os/main/issues/644
=> feat(revert): "add udev rules for linksys ae1200 usb wifi dongle (#214)"

build/ublue-os-just/header.just
Old documentation linked to the now deleted Discourse documentation.  This one is specific to Bluefin, but can also apply as a catch all for all Fedora Atomic images using Just IMO.
=> chore(ujust): Add a better link for ujust's header

build/ublue-os-luks/luks-disable-tpm2-autounlock, build/ublue-os-luks/luks-enable-tpm2-autounlock
luks tpm2 auto lock/unlock scripts should not actually reference ujust since they can be used without it.
if user has found these ujust recipes, it should be obvious what to do from the ujust list of recipes.
Also, why not wipe and re-enroll. 
Closes: #326
=> fix: luks allow wipe for re-enroll and improve prompt/output

build/ublue-os-just/etc-distrobox/distrobox.ini
This completes the move to one image for fedora toolboxes and distroboxes under the ublue-os/toolboxes repo. See [Issue #1 here](https://github.com/ublue-os/toolboxes/issues/1)
=> chore(fedora-distrobox): Moving fedora-distrobox to ublue-os/toolboxes

build/ublue-os-just/06-k8s-dev-tools.just, files/usr/ublue-os/homebrew/kubernetes.Brewfile
`ujust brew` is not a thing anymore and these k8s tools seem to be more fitting upstream, like on Bluefin-dx or Bazzite-dx or something like that. Would that be reasonable? It just feels so out of place here, these werent even referenced anywhere else so...
=> chore: remove k8s tools brew from config ujust

README.md
This PR corrects the pathname for the udev-rules in the readme.
(Correction provided by tulip on [discord](https://discord.com/channels/1072614816579063828/1072617059265032342/1327748396764893294))
=> fix: Correct udev-rules directory name in readme

build/ublue-os-just/00-default.just
it is not really useful anyway
=> chore(just): add no-hostname flag to logs-*-boot

Containerfile
remove opentabletdriver udev rules because it can cause some issue when user want to use pen tablet settings from desktop environment
=> feat: remove opentabletdriver udev rules

build/ublue-os-just/ublue-os-just.spec
tested with `sudo bootc usroverlay`
`just --completions zsh | sed -E 's/([\(_" ])just/\1ujust/g' > _ujust`
`sudo cp _ujust /usr/share/zsh/site-functions`
set zsh as shell in terminal and relaunch
=> feat(just): Generate zsh tab completion for ujust
